<?php

/**
 * @file
 * Contains browser_push_notification.module functionality.
 */

/**
 * Implements hook_page_attachments().
 */
function browser_push_notification_page_attachments(&$page) {
  $page['#attached']['html_head_link'][][] = [
    'rel' => 'manifest',
    'href' => '/manifest.json',
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */

function browser_push_notification_page_attachments_alter(array &$build) {
  
  $build['#attached']['library'][] = 'browser_push_notification/service-worker';
  
}


/**
 * Implements hook__push_notification_theme().
 */

function browser_push_notification_theme($existing, $type, $theme, $path) {
  return array(
    'theme_browser_push_notification' => array(
      'variables' => array('base_path' => base_path()),
    ),
  );
}